export const menuData = [
  {
    bGroup: true,
    iDocType: null,
    iId: 1,
    iParentId: 0,
    iScreenType: 0,
    sIcons: "zmdi zmdi-file",
    sName: "Purchase",
    sUrl: "",
  },
  {
    bGroup: false,
    iDocType: 11,
    iId: 2,
    iParentId: 1,
    iScreenType: 0,
    sIcons: "zmdi zmdi-file",
    sName: "Purchase1",
    sUrl: "",
  },
  {
    bGroup: false,
    iDocType: 12,
    iId: 3,
    iParentId: 1,
    iScreenType: 0,
    sIcons: "zmdi zmdi-file",
    sName: "Purchase2",
    sUrl: "",
  },
  {
    bGroup: false,
    iDocType: 13,
    iId: 4,
    iParentId: 1,
    iScreenType: 0,
    sIcons: "zmdi zmdi-file",
    sName: "Purchase3",
    sUrl: "",
  },  {
    bGroup: false,
    iDocType: 14,
    iId: 5,
    iParentId: 1,
    iScreenType: 0,
    sIcons: "zmdi zmdi-file",
    sName: "Purchase4",
    sUrl: "",
  },
];
